# Generated by Django 4.0.2 on 2022-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'A'), ('AB', 'AB'), ('O', 'O')], default=0, max_length=120),
            preserve_default=False,
        ),
    ]
