# Generated by Django 4.0.4 on 2022-04-29 12:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Dr Bezos Mike', max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('about', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=90)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rating', models.IntegerField()),
                ('pricings', models.CharField(default='$1000- $3500', max_length=15)),
                ('schedule', models.CharField(default='Monday, Friday, Saturday', max_length=200)),
                ('specialties', models.CharField(default='Cosmology ChildCare ', max_length=900)),
                ('myeducation', models.CharField(default='Bsc Anatomy', max_length=300)),
                ('myexperience', models.CharField(default='nurse at BlueCare', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=250)),
                ('startDate', models.DateField(blank=True, default=datetime.date.today)),
                ('endDate', models.DateField(blank=True, default=datetime.date.today)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=30)),
                ('startDate', models.DateField(blank=True, default=datetime.date.today)),
                ('endDate', models.DateField(blank=True, default=datetime.date.today)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='doctor.doctorprofile')),
            ],
        ),
    ]
