# Generated by Django 4.0.2 on 2022-04-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorprofile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='payment',
            field=models.CharField(default='$1000- $3500', max_length=15),
        ),
    ]
