# Generated by Django 4.0.2 on 2022-04-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorprofile_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='payment',
            new_name='pricings',
        ),
    ]
