# Generated by Django 4.0.2 on 2022-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorprofile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialties',
            field=models.CharField(default='Cosmology ChildCare ', max_length=900),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
