# Generated by Django 4.0.2 on 2022-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_education_doctor_alter_experience_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='myeducation',
            field=models.CharField(default='Bsc Anatomy', max_length=300),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='myexperience',
            field=models.CharField(default='nurse at kopioko', max_length=300),
        ),
    ]
